// Applies the Android changes the app needs on top of the files generated by
// `flutter create`. Safe to run more than once.
//
//   dart run tool/patch_android.dart
//
// - MainActivity extends FlutterFragmentActivity (local_auth)
// - permissions: INTERNET (Drive in release), ACCESS_NETWORK_STATE, USE_BIOMETRIC
// - AppCompat launch theme + dependency (local_auth on Android 8 and below)
// - minSdk 24 (local_auth 3.x)
import 'dart:io';

void main() {
  _patchMainActivity();
  _patchManifest();
  _patchStyles();
  _patchGradle();
  stdout.writeln('Android project patched.');
}

void _patchMainActivity() {
  final dir = Directory('android/app/src/main');
  final files = dir
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('MainActivity.kt'));
  for (final file in files) {
    final text = file.readAsStringSync();
    if (text.contains('FlutterFragmentActivity')) continue;
    file.writeAsStringSync(text
        .replaceAll(
          'io.flutter.embedding.android.FlutterActivity',
          'io.flutter.embedding.android.FlutterFragmentActivity',
        )
        .replaceAll(': FlutterActivity()', ': FlutterFragmentActivity()'));
  }
}

void _patchManifest() {
  final file = File('android/app/src/main/AndroidManifest.xml');
  final text = file.readAsStringSync();
  const permissions = [
    'android.permission.INTERNET',
    'android.permission.ACCESS_NETWORK_STATE',
    'android.permission.USE_BIOMETRIC',
  ];
  final missing = permissions.where((p) => !text.contains('"$p"')).toList();
  if (missing.isEmpty) return;
  final lines =
      missing.map((p) => '    <uses-permission android:name="$p"/>').join('\n');
  final manifestTag = RegExp(r'<manifest[^>]*>').firstMatch(text)!;
  file.writeAsStringSync(
    '${text.substring(0, manifestTag.end)}\n$lines'
    '${text.substring(manifestTag.end)}',
  );
}

void _patchStyles() {
  for (final path in [
    'android/app/src/main/res/values/styles.xml',
    'android/app/src/main/res/values-night/styles.xml',
  ]) {
    final file = File(path);
    if (!file.existsSync()) continue;
    final text = file.readAsStringSync();
    file.writeAsStringSync(text
        .replaceAll('@android:style/Theme.Light.NoTitleBar',
            'Theme.AppCompat.Light.NoActionBar')
        .replaceAll('@android:style/Theme.Black.NoTitleBar',
            'Theme.AppCompat.NoActionBar'));
  }
}

void _patchGradle() {
  final kts = File('android/app/build.gradle.kts');
  final groovy = File('android/app/build.gradle');
  if (kts.existsSync()) {
    var text = kts.readAsStringSync();
    text = text.replaceAll('minSdk = flutter.minSdkVersion', 'minSdk = 24');
    if (!text.contains('androidx.appcompat:appcompat')) {
      text += '\ndependencies {\n'
          '    implementation("androidx.appcompat:appcompat:1.7.0")\n'
          '}\n';
    }
    kts.writeAsStringSync(text);
  } else if (groovy.existsSync()) {
    var text = groovy.readAsStringSync();
    text = text.replaceAll('minSdkVersion flutter.minSdkVersion', 'minSdkVersion 24');
    text = text.replaceAll('minSdk = flutter.minSdkVersion', 'minSdk = 24');
    if (!text.contains('androidx.appcompat:appcompat')) {
      text += "\ndependencies {\n"
          "    implementation 'androidx.appcompat:appcompat:1.7.0'\n"
          "}\n";
    }
    groovy.writeAsStringSync(text);
  }
}
