// Applies the Android changes the app needs on top of the files generated by
// `flutter create`. Safe to run more than once.
//
//   dart run tool/patch_android.dart
//
// - MainActivity extends FlutterFragmentActivity (local_auth)
// - permissions: INTERNET (Drive in release), ACCESS_NETWORK_STATE,
//   USE_BIOMETRIC, POST_NOTIFICATIONS (reminders on Android 13+)
// - <queries> for upi:// so UPI apps can be opened (Android 11+)
// - core library desugaring (flutter_local_notifications)
// - AppCompat launch theme + dependency (local_auth on Android 8 and below)
// - minSdk 24 (local_auth 3.x)
// - release signing from android/key.properties (see docs/RELEASE.md)
import 'dart:io';

void main() {
  _patchMainActivity();
  _patchManifest();
  _patchStyles();
  _patchGradle();
  stdout.writeln('Android project patched.');
}

void _patchMainActivity() {
  final dir = Directory('android/app/src/main');
  final files = dir
      .listSync(recursive: true)
      .whereType<File>()
      .where((f) => f.path.endsWith('MainActivity.kt'));
  for (final file in files) {
    final text = file.readAsStringSync();
    if (text.contains('FlutterFragmentActivity')) continue;
    file.writeAsStringSync(text
        .replaceAll(
          'io.flutter.embedding.android.FlutterActivity',
          'io.flutter.embedding.android.FlutterFragmentActivity',
        )
        .replaceAll(': FlutterActivity()', ': FlutterFragmentActivity()'));
  }
}

void _patchManifest() {
  final file = File('android/app/src/main/AndroidManifest.xml');
  final text = file.readAsStringSync();
  const permissions = [
    'android.permission.INTERNET',
    'android.permission.ACCESS_NETWORK_STATE',
    'android.permission.USE_BIOMETRIC',
    'android.permission.POST_NOTIFICATIONS',
  ];
  var out = text;
  final missing = permissions.where((p) => !out.contains('"$p"')).toList();
  if (missing.isNotEmpty) {
    final lines = missing
        .map((p) => '    <uses-permission android:name="$p"/>')
        .join('\n');
    final manifestTag = RegExp(r'<manifest[^>]*>').firstMatch(out)!;
    out = '${out.substring(0, manifestTag.end)}\n$lines'
        '${out.substring(manifestTag.end)}';
  }
  if (!out.contains('android:scheme="upi"')) {
    const upiIntent = '''
        <intent>
            <action android:name="android.intent.action.VIEW"/>
            <data android:scheme="upi"/>
        </intent>''';
    out = out.contains('<queries>')
        ? out.replaceFirst('<queries>', '<queries>\n$upiIntent')
        : out.replaceFirst(
            '</manifest>',
            '    <queries>\n$upiIntent\n    </queries>\n</manifest>',
          );
  }
  if (out != text) file.writeAsStringSync(out);
}

void _patchStyles() {
  for (final path in [
    'android/app/src/main/res/values/styles.xml',
    'android/app/src/main/res/values-night/styles.xml',
    'android/app/src/main/res/values-v31/styles.xml',
    'android/app/src/main/res/values-night-v31/styles.xml',
  ]) {
    final file = File(path);
    if (!file.existsSync()) continue;
    final text = file.readAsStringSync();
    file.writeAsStringSync(text
        .replaceAll('@android:style/Theme.Light.NoTitleBar',
            'Theme.AppCompat.Light.NoActionBar')
        .replaceAll('@android:style/Theme.Black.NoTitleBar',
            'Theme.AppCompat.NoActionBar'));
  }
}

void _patchGradle() {
  final kts = File('android/app/build.gradle.kts');
  final groovy = File('android/app/build.gradle');
  if (kts.existsSync()) {
    var text = kts.readAsStringSync();
    text = text.replaceAll('minSdk = flutter.minSdkVersion', 'minSdk = 24');
    if (!text.contains('isCoreLibraryDesugaringEnabled')) {
      text = text.replaceFirst(
        'compileOptions {',
        'compileOptions {\n        isCoreLibraryDesugaringEnabled = true',
      );
      if (!text.contains('isCoreLibraryDesugaringEnabled')) {
        stderr.writeln('WARNING: compileOptions not found; '
            'core library desugaring is not enabled.');
      }
    }
    if (!text.contains('androidx.appcompat:appcompat')) {
      text += '\ndependencies {\n'
          '    implementation("androidx.appcompat:appcompat:1.7.0")\n'
          '    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.1.4")\n'
          '}\n';
    }
    kts.writeAsStringSync(_addReleaseSigning(text));
  } else if (groovy.existsSync()) {
    stderr.writeln('WARNING: Groovy build.gradle found; release signing '
        'is only patched for build.gradle.kts.');
    var text = groovy.readAsStringSync();
    text = text.replaceAll('minSdkVersion flutter.minSdkVersion', 'minSdkVersion 24');
    text = text.replaceAll('minSdk = flutter.minSdkVersion', 'minSdk = 24');
    if (!text.contains('androidx.appcompat:appcompat')) {
      text += '\ndependencies {\n'
          "    implementation 'androidx.appcompat:appcompat:1.7.0'\n"
          '}\n';
    }
    groovy.writeAsStringSync(text);
  }
}

/// Release builds are signed with the upload key from `android/key.properties`
/// (written by CI from GitHub secrets, never committed). Without that file
/// they fall back to the debug key so `flutter build apk --release` still works.
String _addReleaseSigning(String text) {
  if (text.contains('keystorePropertiesFile')) return text;

  const imports = 'import java.io.FileInputStream\n'
      'import java.util.Properties\n\n';
  const loadProperties = '''
val keystorePropertiesFile = rootProject.file("key.properties")
val keystoreProperties = Properties()
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(FileInputStream(keystorePropertiesFile))
}

''';
  const signingConfigs = '''
    signingConfigs {
        create("release") {
            keyAlias = keystoreProperties.getProperty("keyAlias")
            keyPassword = keystoreProperties.getProperty("keyPassword")
            storeFile = keystoreProperties.getProperty("storeFile")?.let { file(it) }
            storePassword = keystoreProperties.getProperty("storePassword")
        }
    }

''';

  var out = imports + text;
  out = out.replaceFirst('\nandroid {', '\n${loadProperties}android {');
  out = out.replaceFirst('    buildTypes {', '$signingConfigs    buildTypes {');
  out = out.replaceFirst(
    'signingConfig = signingConfigs.getByName("debug")',
    'signingConfig = if (keystorePropertiesFile.exists()) '
        'signingConfigs.getByName("release") '
        'else signingConfigs.getByName("debug")',
  );
  if (!out.contains('signingConfigs.getByName("release")')) {
    stderr.writeln('WARNING: could not find the release signingConfig line; '
        'release builds will use the default signing.');
  }
  return out;
}
